name: "Server image CI/CD"

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  mlflowserver:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create short SHA
        uses: benjlevesque/short-sha@v1.2
        id: short-sha
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.ORG_PAT }}
      - name: Build & Push docker image to github container registry
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./
          file: ./docker/mlflowserver/Dockerfile
          tags: |
            ghcr.io/mlops-for-all/mlflowserver:latest
            ghcr.io/mlops-for-all/mlflowserver:${{ steps.short-sha.outputs.sha }}
          build-args: |
            BASE_CONTAINER=python:3.7
